module.exports = {
    WE_DAKA_KEY_GROUPS: 'WE_DAKA_GROUPS',
    WE_DAKA_KEY_STYLE: 'WE_DAKA_STYLE',
    WE_DAKA_KEY_GROUP_STATUS:'WE_DAKA_KEY_GROUP_STATUS',
    WE_DAKA_KEY_GROUP_CALENDAR:'WE_DAKA_KEY_GROUP_CALENDAR',
    WE_DAKA_KEY_FEED: 'WE_DAKA_KEY_FEED',
    WE_DAKA_KEY_GROUP_EXPORT_LIMIT:'WE_DAKA_KEY_GROUP_EXPORT_LIMIT',
    WE_DAKA_ERROR_NETWORK: '网络异常,请稍后重试',
    WE_DAKA_ERROR_SERVICE: '系统开小差了,请稍后重试',
};